# Generated by Django 4.2.6 on 2023-10-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("reward", models.CharField(max_length=100)),
                ("tech_stack", models.CharField(max_length=100)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobs.company")),
                ("user_job", models.ManyToManyField(to="jobs.user")),
            ],
            options={
                "db_table": "job",
            },
        ),
    ]
